# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='depart',
            new_name='depart_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='return_date',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
