# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20180409_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user_trips',
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to='exam.User'),
        ),
    ]
